name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.3']

    steps:
    - uses: actions/checkout@v3
    - uses: devcontainers/ci@v0.3
      name: Pre-build image and run make ci-build in dev container
      with:
        imageName: ghcr.io/opencodeco/testcontainers-php-devcontainer
        cacheFrom: ghcr.io/opencodeco/testcontainers-php-devcontainer
        push: always
        runCmd: composer test
